FROM ubuntu:16.04
MAINTAINER Alex Usha <au@ontix.ru>

RUN echo "resolvconf resolvconf/linkify-resolvconf boolean false" | debconf-set-selections

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install \
  wget \
  dialog \
  openssh-client \
  software-properties-common \
  dnsmasq \
  dnsutils \
  net-tools \
  sudo \
  rsyslog \
  unzip \
  openssh-server \
  nano

RUN sed -i 's/#PasswordAuthentication\ yes/PasswordAuthentication\ no/' /etc/ssh/sshd_config

#VOLUME ["$HOSTNAME:/opt/zimbra"]

EXPOSE 22 25 465 587 110 143 993 995 80 443 8080 8443 7071

COPY opt /opt/

COPY etc /etc/

CMD ["/bin/bash", "/opt/start.sh", "-d"]
